import type { ExpectedHashes, KernelId } from "./types";

/**
 * Frozen REPROGPU pins (wave 48). Generated by `bun run scripts/reprogpu-evidence.ts`
 * from the shipped reference implementations, then committed by hand: the permanent
 * gate recomputes every value and compares, so there is no auto-update path.
 * The hashes are SHA-256 over the little-endian byte serialization of each
 * kernel's reference output (see the amended spec, section 2).
 */
export const EXPECTED_HASHES: ExpectedHashes = {
  counts: { K1: 4104, K2: 65536, K3: 65536, K4: 16385, K5: 65536 },
  hashes: {
    K1: "c046384ed6580b8111b8ef34f5d0932289209f4920666477bc76ffe724dfa27a",
    K2: "f9004cf3ed50db5cdb6351a3eb090a498586ade2e3f7499744c951bf77f86d01",
    K3: "fbe13a3b4e2fc7bf3a4b38c838912651151c03460bd9d1d7f1ea81190af3932e",
    K4: "eea119f4059566875ceaf784400d519fd8ff2148d9f221e0004fd04944a21797",
  },
} as const;

/** K1 flag vector (finite words plus +Inf and NaN): flags must read as 1. */
export const EXPECTED_K1_FLAG_HASH =
  "cc7dca6d69fec7162cf610b0170076aec74d3d5bec47b2ea80d0b74afb3c9ecb";

/** SHA-256 of the exact 1 MiB K4 message, from an independent oracle. */
export const EXPECTED_K4_DIGEST =
  "79bfb41c6346bc10d842265e62eb4e35ce77ac3bc2d3c21ebe068d808acc1361";

/** SHA-256 of each pinned WGSL source after CRLF-to-LF normalization. */
export const EXPECTED_WGSL: Readonly<Record<KernelId, string>> = {
  K1: "ea7c46670ea2a3258b7522db6a8b09af1f2e7895021870a32669ca7ec9b2df3f",
  K2: "010e4d4db8cc43cf95f9d4329da09d5bd3a4d3d764c20d63490df81c6c0d4dbe",
  K3: "1013c964ff0a25721558503d391bd6630e96f848973c7198668dfcd14988132d",
  K4: "d9d8db073c560de60fead78f846afbb4feec2b2626d2d74c072ed6a1c6b23489",
  K5: "3f003ca3d1bba17b2052b5cba08a42211eba3fae742177ad52d9f109541e3cbe",
} as const;
